name: app_i_never
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.8.1

dependencies:
  awesome_dialog: ^2.1.2
  bordered_text: ^2.0.0
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  faker: ^2.0.0
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.3+2
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  intl: ^0.17.0
  mobx: ^2.0.6+1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  mobx_codegen: ^2.0.5+2

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Valden
      fonts:
        - asset: assets/Valden.otf
  assets:
    - assets/mugs.png
